### ISSUE TITLE
Pitch to news sites?

### ISSUE THREAD

**Issue by upintheairsheep** [TheTechRobo/youtubevideofinder#10]
Should I pitch this project to multiple news sites including 9to5Google, or would you like to pitch it later, when bugs are fixed and issues are ironed out, or not at all because the server be too much under load?

**Comment by TheTechRobo** [comment]
I'll think about this, doubt news sites will care much (this is kind of a niche project) but yeah would probably have to be later, after the rewrite. I'd also have to do some stress testing and speed up the code. (Also will need @ivan 's approval , he might not like drawing attention to `#youtubearchive`.)

**Comment by upintheairsheep** [comment]
OK. To preserve your sanity it will be a no for now.

**Comment by upintheairsheep** [comment]
They might be interested because it is quite a useful tool!

**Comment by TheTechRobo** [comment]
Keeping this open since we haven't actually decided yet - this is just put off.

**Comment by upintheairsheep** [comment]
I found this tool really useful by the way.

**Comment by TheTechRobo** [comment]
Cool, thanks for the kind words! :-)

**Comment by upintheairsheep** [comment]
Notice: The Samsung Smart TV app store web version is starting to break down, and is likely to be removed in the coming weeks. Please write a snscrape based extractor, and possibly a gallery-dl extractor as well. See https://hackint.logs.kiska.pw/archiveteam-bs/20221116

https://github.com/JustAnotherArchivist/snscrape/issues/591
https://github.com/mikf/gallery-dl/issues/3069

**Comment by TheTechRobo** [comment]
It looks like the site handles load decently. I couldn't find a memory problem, at least...

I will look into making the code run faster, though.

**Comment by TheTechRobo** [comment]
Just realised I never got back about this. Doing that should be fine, I don’t really care either way. The server should be able to handle it reasonably well, so Share it with whoever you want. Just don’t DDoS me :-)

you should probably check with #youtubearchive first, though, as they might not want extra attention. 

Closing this issue.
