### ISSUE TITLE
Filmot JSON error

### ISSUE THREAD

**Issue by asd234438** [TheTechRobo/youtubevideofinder#110]
I applied for the Filmot api beta, got an api key, added to the config.yml file, built the image. Everytime I try searching for a video I get this error in the Filmot subsection: "An error occured while retrieving data from Filmot.: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')". 
config.yml: 
...
  filmot:
    title: Filmot
    enabled: true
    api_key: "API_KEY"
...

**Comment by TheTechRobo** [comment]
You're probably being blocked by cloudflare. You'll need to ask the owner of Filmot to be whitelisted.

**Comment by asd234438** [comment]
I looked at the Filmot class and I see the issue now: I got a Filmot API Rapidapi key and your program uses the filmot.com api from the website itself. I was under the false impression that the Rapidapi api was the only one. I apologize.

**Comment by TheTechRobo** [comment]
Ah. I don't currently have access to that API, but if you can give some example code for the RapidAPI version, I can try and add support for it.
