### ISSUE TITLE
Detect comments in Internet Archive?

### ISSUE THREAD

**Issue by upintheairsheep** [TheTechRobo/youtubevideofinder#16]
https://ia601408.us.archive.org/8/items/youtube-0WZ4uLFTHEE/0WZ4uLFTHEE.info.json includes comments while anything that has comments in the info empty doesn’t

**Comment by TheTechRobo** [comment]
Uhh I'm not sure

This would mean an extra request to IA. Considering how slow it is, this might not be a great idea.

**Comment by TheTechRobo** [comment]
Going to close this, if there's a way to do this that won't decrease the speed, lmk and I'll reopen the issue
