### ISSUE TITLE
Support: ArchiveTeam Hungary Lecsu "private archive"

### ISSUE THREAD

**Issue by upintheairsheep** [TheTechRobo/youtubevideofinder#18]
Please tell archiveteam hungary to add an api to retrieve weather the videos are in the private archive, and the name of erroneous submissions (videos that were deleted or private before any archival was possible) and rejected ones.

**Comment by TheTechRobo** [comment]
You can ask them yourself - I probably won't. I'm not against adding support if they do add an API, but as it's a private archive, I'm not sure they'll want it

**Comment by TheTechRobo** [comment]
If they decide to add an API for this, comment and I'll reopen the issue.
