### ISSUE TITLE
Change out the "irc ettiquete" link

### ISSUE THREAD

**Issue by TheTechRobo** [TheTechRobo/youtubevideofinder#25]
It's causing problems because there's a link to the `#archiveteam` webchat, which is causing people who don't know what they're doing to think that that's `#youtubearchive`.

https://hackint.logs.kiska.pw/archiveteam/20230129#c337004

**Comment by JaxonPlays** [comment]
Pretty simple fix such as making a `#youtubearchive` a hyperlink that directs you to:

https://webirc.hackint.org/#irc://irc.hackint.org/youtubearchive

**Comment by TheTechRobo** [comment]
IIRC `#youtubearchive` asked me not to do that.

**Comment by TheTechRobo** [comment]
No longer relevant - IRC is not directly mentioned on the site anymore.
