### ISSUE TITLE
Use flexbox or something

### ISSUE THREAD

**Issue by TheTechRobo** [TheTechRobo/youtubevideofinder#38]
The current css is awful to read and doesn't respond that well

**Comment by UdhbhavSinghRana** [comment]
What type of ui does the site can you provide some example?

**Comment by TheTechRobo** [comment]
The current UI is fine (though a bit ugly); I'm not a UX designer so I don't know how to improve it further. The problem here is that the code relies a lot on absolute positioning (i.e. "put this section 70% of the way down the screen") which is hard to read and hard to change.

**Comment by UdhbhavSinghRana** [comment]
ok i will see what i can do :)

**Comment by UdhbhavSinghRana** [comment]
![Screenshot from 2023-07-10 12-57-34](https://github.com/TheTechRobo/youtubevideofinder/assets/102753277/3ef1f56c-ef5b-40f9-93a8-f406fb88fb56)
is this ok?
