### ISSUE TITLE
Add a way to find if a video's thumbnail is archived on IA

### ISSUE THREAD

**Issue by kayleeqt** [TheTechRobo/youtubevideofinder#49]
Various videos have thumbnails archived in the 5 different ytimg domains (i, i1, i2, i3 and i4) as well as img.youtube.com
A way for the finder to detect if the thumbnails have been archived under these domains would be useful, or at least links to be able to access these in an easy way, with the `https://web.archive.org/web/*/[domain here]/vi/IN5MCEDMxkc/*` link format.

There are also sometimes thumbnails archived when replacing the `vi` with `vi_webp` in the `i.ytimg.com` domain.
There are also (very rarely) thumbnails archived under the `ytimg.googleusercontent.com` domain.

**Comment by TheTechRobo** [comment]
This is a good idea! How do you suggest it should be shown on the site, though?

**Comment by pixelkaylee** [comment]
Possibly under the "Wayback Machine" section it could display the i1-4 and img.youtube links and (if possible) determine if any of those domains have any page archived
