### ISSUE TITLE
GhostArchive sometimes has false alarms when archival failed

### ISSUE THREAD

**Issue by TheTechRobo** [TheTechRobo/youtubevideofinder#50]
Example video ID: zY57Aw4ik3w

**Comment by JaxonPlays** [comment]
Maybe use the BeautifulSoup library to see if Heading 1 contains `Archiving error` then print `Not Available`.

**Comment by TheTechRobo** [comment]
That is possible, but might be CPU-intensive. Perhaps it could be done just by doing a search of the HTML rather than trying to parse it. I also notice that there is 

This bug also occurs when archival is stuck. I've seen videos where archival never finishes, it never switches from the "Archiving..." page.

**Comment by TheTechRobo** [comment]
This seems to have been fixed by GhostArchive. I now see a 500 error on my test case, not sure if that is the case for all failed videos. But I am adding a basic assertion just to make sure.
