### ISSUE TITLE
Could you please add in a typical video search engine to the website please.

### ISSUE THREAD

**Issue by KaineRecycler** [TheTechRobo/youtubevideofinder#79]
I would like to contribute a new feature for your website so for my first contribution is that could you add in a standard search engine for searching for video and metadata content please let me know if you could make it more accessible by adding in a video key phrase search engine that kinda looks alike Google video search please from Kaine Dube.

**Comment by TheTechRobo** [comment]
Do you mean allowing people to search for videos by e.g. title?

**Comment by KaineRecycler** [comment]
Well like that but by keyword phrase search.
So anyway I hope this helps other users with finding all content from YouTube with this new feature.

**Comment by KaineRecycler** [comment]
Anyway do you don't mind if I am looking to able to fork this tool and make it customization for my interest and to my needs please.
Only if you could get me permission to do so by providing your link to your tool and your website and source code for your website
So that I can create a customized version of the same tool but with the help from forking this project please.

**Comment by TheTechRobo** [comment]
That's fine, as per the licence, though I wouldn't mind if you submitted useful changes as pull requests :-)

**Comment by KaineRecycler** [comment]
Thank you very much ☺️.
