### ISSUE TITLE
It doesn't say when #youtubearchive has something or not, please fix this.

### ISSUE THREAD

**Issue by Trevorthedestroyer** [TheTechRobo/youtubevideofinder#84]
I know for a fact that I entered this earlier and it said #youtubearchive had it.
![Screenshot 2024-04-07 4 17 22 PM](https://github.com/TheTechRobo/youtubevideofinder/assets/136278567/2c03b85e-e5a1-4f4a-9ad2-7ce4ec903197)

**Comment by TheTechRobo** [comment]
Please provide the YouTube URL, copypastable. This looks like it's on their end but I am not 100% sure that I read the ID correctly.

**Comment by Trevorthedestroyer** [comment]
Here: https://www.youtube.com/watch?v=OknsFJQOtiI. I did some searching and it turns out most (Probably all) of the "Not Available" links show up are from sketch: https://www.youtube.com/channel/UCfw6CRDOg5xQsB-2QNC_KUA

**Comment by TheTechRobo** [comment]
Confirmed that https://www.youtube.com/watch?v=OknsFJQOtiI does not register as archived through the IRC bot. This is on #youtubearchive's end - if you believe it to be an error, you should get in touch with them.
