### ISSUE TITLE
How to retrieve videos from #youtubearchive?

### ISSUE THREAD

**Issue by Zamy846692** [TheTechRobo/youtubevideofinder#91]
According to YouTube Video Finder a YouTube video (https://www.youtube.com/watch?v=R_lMdm0BRJI) I have been trying to find for ages now - and have been unable to find anywhere else is marked as "Available" on #youtubearchive, but it doesn't give a link of any kind I can use to download it. Is there any way I can actually get hold of it?

> #youtubearchive: Available
At the request of #youtubearchive's maintainer, instructions to request videos have been removed. If you are significantly involved in archiving or open source, you have a legitimate research or humanitarian purpose, or are able to contribute materially, contact me at thetechrobo@proton.me.

Is there any way you can help me? this is really important to me and I want to preserve it so that we can all see it again.
Help me. You're my only hope!

**Comment by TheTechRobo** [comment]
Can we take this to email? You can use the address mentioned in message (thetechrobo@proton.me).

**Comment by Zamy846692** [comment]
I sent the email - from `Whipped.breen@protonmail.com`

**Comment by TheTechRobo** [comment]
Alright. I might take a week or two to reply as I am currently having some issues with my infrastructure.

Closing the issue.

**Comment by MSOB7YY** [comment]
sorry to bring this back up, i also found some videos available on #youtubearchive only, is it a closed distributed videos or something? if thats the case is it accessible to normal ppl? thanks for the awesome site btw <3
